### ISSUE TITLE
Labor Hour Input by Size Type 

### ISSUE THREAD

**Issue by ImTaki** [ImTaki/OPERA#21]
> User want to input labor hour by size type
> They want to batch add or add individually

This is some difference between full OPERA and manual OPERA.

Full OPERA labor input is by PO. Manual OPERA labor input by size type.

**Comment by Taki-Guan** [comment]
This feature has been finished.

**Comment by ImTaki** [comment]
The actual business requirement has been changed into labor hour input by each SKU
